version: '3.7'

services:
    # MySQL Server
    database:
        image: 'mysql:latest'
        container_name: drum-n-code
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - ${MYSQL_PORT}:3306
